update

diff --git a/meta-openpli/recipes-support/openvpn/openvpn/openvpn b/meta-openpli/recipes-support/openvpn/openvpn/openvpn
--- a/meta-openpli/recipes-support/openvpn/openvpn/openvpn
+++ b/meta-openpli/recipes-support/openvpn/openvpn/openvpn
@@ -4,7 +4,6 @@
 # <rob@mars.org>, edited by iwj and cs
 # Modified for openvpn by Alberto Gonzalez Iniesta <agi@agi.as>
 # Modified for restarting / starting / stopping single tunnels by Richard Mueller <mueller@teamix.net>
-# Modified for respecting pid file on service start by Fabian Klemp <fabian.klemp@axino-group.com>
 
 test $DEBIAN_SCRIPT_DEBUG && set -v -x
 
@@ -15,25 +14,10 @@ test -d $CONFIG_DIR || exit 0
 
 start_vpn () {
     modprobe tun >/dev/null 2>&1 || true
-    # make sure the device node exists
-    if [ ! -c /dev/net/tun ]; then
-        if [ ! -d /dev/net ]; then
-            mkdir /dev/net
-        fi
-        mknod /dev/net/tun c 10 200
-        chmod 600 /dev/net/tun
-    fi
-    start-stop-daemon --start --quiet --pidfile /var/run/openvpn.$NAME.pid \
-            --exec $DAEMON -- \
-            --daemon --writepid /var/run/openvpn.$NAME.pid \
-            --config $CONFIG_DIR/$NAME.conf --cd $CONFIG_DIR || rc="$?"
-    case $rc in
-        1) echo -n " ALREADY STARTED->";;
-        3) echo -n " FAILED->";;
-    esac
+    $DAEMON --daemon --writepid /var/run/openvpn.$NAME.pid \
+            --config $CONFIG_DIR/$NAME.conf --cd $CONFIG_DIR || echo -n " FAILED->"
     echo -n " $NAME"
 }
-
 stop_vpn () {
    kill `cat $PIDFILE` || true
   rm $PIDFILE
